// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYykLu_nnHR7hdP_92SGpg4Dj_XgA2qJ8',
    appId: '1:671244452078:web:556748e18be2c8330733ff',
    messagingSenderId: '671244452078',
    projectId: 'yosef-exam-system',
    authDomain: 'yosef-exam-system.firebaseapp.com',
    storageBucket: 'yosef-exam-system.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4AMalz8T-7AIq49WiZYWbsNQBPUjaPC8',
    appId: '1:671244452078:android:5224e39f146b84eb0733ff',
    messagingSenderId: '671244452078',
    projectId: 'yosef-exam-system',
    storageBucket: 'yosef-exam-system.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzEspOl6Vo3ZE4DnpY5e9U4m4rgyYvmy4',
    appId: '1:671244452078:ios:541e3b6c542f50060733ff',
    messagingSenderId: '671244452078',
    projectId: 'yosef-exam-system',
    storageBucket: 'yosef-exam-system.firebasestorage.app',
    iosBundleId: 'com.example.yosefExaminationSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzEspOl6Vo3ZE4DnpY5e9U4m4rgyYvmy4',
    appId: '1:671244452078:ios:541e3b6c542f50060733ff',
    messagingSenderId: '671244452078',
    projectId: 'yosef-exam-system',
    storageBucket: 'yosef-exam-system.firebasestorage.app',
    iosBundleId: 'com.example.yosefExaminationSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYykLu_nnHR7hdP_92SGpg4Dj_XgA2qJ8',
    appId: '1:671244452078:web:556748e18be2c8330733ff',
    messagingSenderId: '671244452078',
    projectId: 'yosef-exam-system',
    authDomain: 'yosef-exam-system.firebaseapp.com',
    storageBucket: 'yosef-exam-system.firebasestorage.app',
  );
}
